boostorg/mpl

test/aux_/increased_arity.cpp
Avoiding compile errors on visual studio compilers. Errors were due to the way MPL_ASSERT is defined for these compilers.
All tests were verified to pass on MSVC 2010.
@mclow could you please merge this fix?
=> Fix to pull request #13 

include/boost/mpl/aux_/insert_range_impl.hpp, include/boost/mpl/map/aux_/insert_range_impl.hpp, include/boost/mpl/map/map0.hpp, include/boost/mpl/set/aux_/insert_range_impl.hpp, include/boost/mpl/set/set0.hpp, test/insert_range.cpp
According to reference, insert_range should work for any Extensible
sequence or Extensible Associative sequence, but the default
implementation of insert_range_impl assumes a front_inserter is defined
for the given sequence, but neither Extensible nor every Extensible
Associative sequences are required to also be a Front Extensible
sequence. This fix rely only on insert, which is defined for every
Extensible sequence.
=> Fix to Ticket #11001

include/boost/mpl/empty_sequence.hpp, include/boost/mpl/map/aux_/item.hpp, include/boost/mpl/set/aux_/item.hpp, test/empty_sequence.cpp, test/filter_view.cpp, test/joint_view.cpp, test/map.cpp, test/set.cpp, test/single_view.cpp, test/transform_view.cpp
The fix is based on the report of Ticket 8749 itself:
>I have traced the problem to the file boost/mpl/map/aux_/item.hpp in the class definition of m_item. m_item derives from Base (which is a map<...> type) but does not define a "typedef m_item type;" to act as a unary metafunction returning itself. The result is that Base::type is found instead which means that m_item acts as a unary metafunction returning a map with all the inserted elements removed. The class m_item_ at the bottom of the file properly defines a "typedef m_item_ type;" which strengthens my belief that it missing from m_item is a bug.
Originally Tickets 7975 and 8749 referred only to insertion of keys into maps, but the very same bug can be reproduced for sets as well. Moreover, the removal of keys from both also …
=> Fix to Tickets #7975 and #8749 - Branched off from develop

preprocessed/README.txt, preprocessed/boost_mpl_preprocess.py
* Added default-value for cmdline-option which expects the Boost
source-directory. It points to the Boost source-directory in which the
script "boost_mpl_preprocess.py" is located.
* Adjusted "README.txt" file to reflect these changes.
Signed-off-by: Deniz Bahadir <dbahadir@benocs.com>
=> Addition to fix / workaround for issue #11224.

doc/src/refmanual/Iterators.rst
Reverts boostorg/mpl#23 - shouldn't go into master
=> Revert "fix typo"

include/boost/mpl/print.hpp
Including `boost/mpl/print.hpp` on Clang in C++03 mode **always** produces a warning (i.e. even without using `boost::mpl::print<T>`).
We can remove the warning by adding 
```
#pragma clang diagnostic ignored "-Wc++11-extensions"
```
Note that `-Wc++11-extensions` is not supported in Clang older than 3.0, but this is not an issue since the current `boost::mpl::print` implementation requires Clang 3.0 or newer versions and results in errors in Clang older than 3.0. 
This issue was reported by Richard Hadsell on Boost developer ML.
=> Fix "-Wc++11-extensions" warning on Clang in C++03 mode

preprocessed/boost_mpl_preprocess.py
(e.g.) with i = 110 the script created 10100 instead:
line = re.sub(r'20', re.escape(str(i+10)), line.rstrip())
20 -> 110
line = re.sub(r'11', re.escape(str(i + 1)), line.rstrip())
110 -> 1010
line = re.sub(r'10(?![0-9])', re.escape(str(i)), line.rstrip())
1100 -> 10100
=> Fixed a bug with the template substitution adding temporary string

include/boost/mpl/assert.hpp
Add PGI C++ to list of compilers that use enums rather than static constants for compile-time assertions, because, like GCC, PGI issues warnings for unused static constants.
=> Update PGI C++ compiler support

include/boost/mpl/assert.hpp
Same as #33 but ignore warning instead of "fixing" it.
=> Ignore gcc 8 warnings.

include/boost/mpl/assert.hpp, test/Jamfile.v2, test/assert_vc8.hpp, test/assert_vc8_p1.cpp, test/assert_vc8_p2.cpp
The struct member function inside BOOST_MPL_ASSERT_MSG_IMPL was causing
multiple definitions of the same symbol when used inside e.g. template
functions.
An example of where this is a big issue is in the boost/geometry library
where you currently only can call each function once for each geometry
or you get hit by the multiple definitions linking error.
This fix* works around the issue by gracefully degrading to
BOOST_STATIC_ASSERT_MSG instead of failing during linking.
=> Fix BOOST_MPL_ASSERT_MSG for VC++8

CMakeLists.txt
This cmake file just provides the minimal infrastructure necessary, such that other libraries can get a sensible result from calling
add_subdirectory( <path-to-boost_mpl> )
target_link_libraries( <my_lib> PUBLIC Boost::mpl )
More information:
- https://groups.google.com/forum/#!topic/boost-developers-archive/kM4JRmyVl3M%5B1-25%5D
- https://groups.google.com/d/msg/boost-developers-archive/4HU-RzReL7U/FS1X6OFrEQAJ
- https://groups.google.com/forum/#!topic/boost-developers-archive/9ZdrVbAn1aU
Of course the file can be extended to e.g. build and run tests and support installation, but that is out of scope for this particular PR.
Note: I haven't yet hooked up the tests to travis for two reasons:
1) frankly, the travis file looks much more complicated than what I'm used to so I'm not sure how …
=> Add minimal cmake file 

include/boost/mpl/aux_/preprocessed/gcc/template_arity.hpp, include/boost/mpl/aux_/template_arity.hpp, include/boost/mpl/aux_/yes_no.hpp
Detect while using boost::transform_iterator in a Boost.Container test
=> Fix some -Wsign-conversion warnings

.github/workflows/ci.yml, include/boost/mpl/assert.hpp
BOOST_GCC is not defined for NVCC, therefore we should use BOOST_GCC_VERSION.
=> Fix -Wparentheses warning not ignored on NVCC

include/boost/mpl/and.hpp, include/boost/mpl/bitand.hpp, include/boost/mpl/bitor.hpp, include/boost/mpl/or.hpp
Fixes issue https://github.com/boostorg/mpl/issues/46
=> Fixes issue 46 with clang and msvc

include/boost/mpl/assert.hpp
=> Fix unused variable warning from BOOST_MPL_ASSERT_* on Clang

include/boost/mpl/assert.hpp
Newer compilers may warn when using `0`, e.g.:
```
./boost/iterator/detail/facade_iterator_category.hpp:161:5: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
BOOST_MPL_ASSERT_NOT((is_iterator_category<Traversal>));
^
./boost/mpl/assert.hpp:324:58: note: expanded from macro 'BOOST_MPL_ASSERT_NOT'
boost::mpl::assert_not_arg( (void (*) pred)0, 1 ) \
```
=> Avoid `Wzero-as-null-pointer-constant` warning

include/boost/mpl/aux_/integral_wrapper.hpp
Trying to form next/prior in constant evaluation may be ill-formed. Fixes #69.
=> Use static const for next/prior from C++11

include/boost/mpl/and.hpp, include/boost/mpl/bitand.hpp, include/boost/mpl/bitor.hpp, include/boost/mpl/or.hpp
Some 3rdparty parsers (e.g. Qt moc) fail to parse the bitand.hpp due to the fact that bitand is a keyword in C++, not a macro. Modern MSVC versions define bitand/bitor only if __cplusplus macro is not defined, see iso646.h: https://pastebin.com/zTcd0juT
Thus, boost can also check the macro only in C mode making moc happy
=> Do not check the bitand/bitor macros in cplusplus mode

preprocessed/boost_mpl_preprocess.py, preprocessed/fix_boost_mpl_preprocess.py, preprocessed/pp.py, preprocessed/preprocess.py
* fixed libraries include
* fixed incorrect usage of python2 string
* fixed python2 to python3 script issues (2to3) like print ""
* fixed data types
* fixed python3 usage of str instead of string (join, split etc.)
* added support to determine the absolute path of the executable
binary of the current Python interpreter
* thx @Bagira80 for his support
Fixes issue: #67
Signed-off-by: Thomas Höhlig <thoehlig@benocs.com>
=> Fix scripts to add python3 support

preprocessed/README.txt, preprocessed/boost_mpl_preprocess.py, preprocessed/fix_boost_mpl_preprocess.py
https://github.com/boostorg/mpl/pull/68 was incomplete; I finished this for modern python3 and checked that the script can run.  The only incompatible issue was that files were opened with "rU" and the "U" is no longer valid.  I updated the README, but I did not regenerate the files.  When I did, it wouldn't build in CI.
This fixes #67
=> Fix preprocessed python3 scripts
